export const STAY_HARD_CHAD = [
  "On my path to reach the place where no developer reached",
  "Unshaken — Arthur Morgan",
  "Never Hesitate, Hesitation is defeat. — Isshin Ashina",
  "A true warrior does not flee from death. — Isshin Ashina",
  "A man must be strong to protect what he loves. — Isshin Ashina",
  "Steel your heart, and the blade shall follow. — Isshin Ashina",
  "When the blood boils, the mind must stay calm. — Isshin Ashina",
  "The path of the shinobi is one of sacrifice. — Sekiro",
  "Do not fear death. Fear dying without purpose. — Sekiro",
  "Resolve turns weakness into strength. — Isshin Ashina",
  "Even in defeat, honor remains. — Sekiro",
  "Discipline is your greatest ally. — Emma",
  "Revenge is a fool’s game. — Arthur Morgan",
  "We can’t change what’s done, we can only move on. — Arthur Morgan",
  "Be loyal to what matters. — Arthur Morgan",
  "You don’t get to live a bad life and have good things happen to you. — Arthur Morgan",
  "I gave you all I had. — Arthur Morgan",
  "Nothing means more to me than this gang. — Arthur Morgan",
  "We can’t fight nature, Arthur. We can’t fight change. — Dutch van der Linde",
  "You either live for something, or you die for nothing. — Arthur Morgan",
  "The world ain’t fair, but you still gotta live in it. — Arthur Morgan",
  "Do your part, and do it well. — Arthur Morgan",
  "A warrior knows peace only in death. — Jin Sakai",
  "Discipline is your greatest weapon. — Lord Shimura",
  "Fight for those who cannot fight for themselves. — Jin Sakai",
  "Honor died on the battlefield. Now, only purpose remains. — Jin Sakai",
  "The Ghost fears nothing. — Jin Sakai",
  "The way of the warrior is found in death. — Bushido",
  "Be like water. Flow through your enemies. — Jin Sakai",
  "A single strike can change fate. — Lord Shimura",
  "Strength is born from endurance. — Jin Sakai",
  "In silence, you find your power. — Jin Sakai",
  "Fear not the dark, my friend. And let the feast begin. — Dark Souls",
  "Only in the face of death do we see life clearly. — Dark Souls",
  "Seek strength, the rest will follow. — Elden Ring",
  "May your path be strewn with light. — Dark Souls",
  "The fire fades, but courage endures. — Dark Souls",
  "Ash seeks embers, and the brave find purpose. — Dark Souls",
  "Death is not the end. It is the trial. — Elden Ring",
  "Do not despair. Persistence is victory. — Elden Ring",
  "In the darkness, we learn to see. — Elden Ring",
  "Those who persist shall transcend. — Dark Souls",
  "Evil is evil. Lesser, greater, middling — makes no difference. — Geralt of Rivia",
  "If I’m to choose between one evil and another, I’d rather not choose at all. — Geralt of Rivia",
  "Fear is your most powerful ally — and your worst enemy. — Vesemir",
  "People like to invent monsters and monstrosities. — Geralt of Rivia",
  "Chaos is everywhere, but so is choice. — Geralt of Rivia",
  "Sometimes, the hardest path is the right one. — Geralt of Rivia",
  "A sword holds no truth, only the hand that wields it does. — Witcher",
  "Courage is not the absence of fear, but mastery over it. — Geralt of Rivia",
  "A wolf does not ask permission to howl. — Witcher",
  "Pain is a teacher none can refuse. — Vesemir",
  "A strong man doesn’t need to read the future. He makes his own. — Solid Snake",
  "Building the future and keeping the past alive are one and the same. — Big Boss",
  "Loyalty to the end — that is the way of a true soldier. — The Boss",
  "War is not freedom. It is the price of it. — Big Boss",
  "We are not tools of the government. — Solid Snake",
  "The world will always need men like us. — Big Boss",
  "A soldier’s heart never dies, even in peace. — Solid Snake",
  "Only through pain can we understand peace. — The Boss",
  "The mission is not over until you draw your last breath. — Solid Snake",
  "Endurance is victory in disguise. — Big Boss",
  "Calm in the storm — that is the way of the warrior.",
  "Fear cuts deeper than any blade.",
  "Even steel must bend before it breaks.",
  "Honor is not given, it is earned in silence.",
  "Victory belongs to those who endure.",
  "The blade is nothing without the hand, and the hand is nothing without the will.",
  "To master the sword, you must first master yourself.",
  "In patience, there is strength.",
  "Walk alone, but never without purpose.",
  "The calm mind slays the fiercest foe.",
  "Suffer the pain of discipline, or suffer the pain of regret.",
  "He who conquers himself is the mightiest warrior. — Confucius",
  "The obstacle is the way. — Marcus Aurelius",
  "Do not pray for an easy life; pray for the strength to endure a hard one. — Bruce Lee",
  "Be still like the mountain, and flow like the river. — Lao Tzu",
  "Waste no more time arguing what a good man should be. Be one. — Marcus Aurelius",
  "The more you sweat in peace, the less you bleed in war.",
  "What stands in the way becomes the way. — Stoic Proverb",
  "Discipline is the highest form of freedom.",
  "Train your mind to stay calm in chaos.",
  "Rise again, no matter how many times you fall.",
  "The battle is won in the mind before it is fought on the field.",
  "A lion does not concern himself with the opinion of sheep.",
  "Fall seven times, stand up eight. — Japanese Proverb",
  "Courage is being scared to death but saddling up anyway. — John Wayne",
  "Victory is reserved for those who are willing to pay its price.",
  "A warrior is not born — he is forged in struggle.",
  "If you stand for nothing, you’ll fall for anything.",
  "Strength is not found in comfort, but in conflict.",
  "There is no growth without struggle.",
  "The world breaks the weak, but the strong learn to bend.",
  "Endure the storm, and you shall command the wind.",
  "Purpose is forged in fire.",
  "Let your scars remind you that you survived.",
  "Every step forward is a battle won.",
  "Even the sharpest blade must be tempered by patience.",
  "Greatness demands the price of pain.",
  "Those who master silence, master strength.",
  "You are the weapon — everything else is just steel.",
  "When you fall, rise sharper than before.",
  "Measure of a man is what he does with his power",
];

export const isDevelopment =
  process.env.NODE_ENV === "development" ||
  (process.env.NODE_ENV === undefined && !process.env.VERCEL);

export const THIRUKKURAL_TAMIL = [
  "உழுதுண்டு வாழ்வாரே வாழ்வார்; மற்றெல்லாம் தொழுதுண்டு பின்செல் பவர்.",
  "உழுவார் உலகத்தார்க்கு ஆனந்தம்; தாங்களும் தம்கடைவாழ் வான்.",
  "உழைப்பின் கண்ணே உயர்வு; உழைக்காதார் கண்ணே தாழ்வு.",
  "தெய்வம் தொழாஅள் கொழுநன் தொழுதெழுவாள் தெய்வம் தொழுதே கிடன்.",
  "ஊழையும் உப்பக்கம் காண்பர்; உழக்கண் முயற்சி உடையார் மேல்.",
  "ஊழினால் வருவதே ஓர்வினை; முயற்சியால் மாற்றி விடல் வேண்டும்.",
  "முயற்சி திருவினை தந்து நிறுத்தும்; முயலாது கிடப்பார்க்கு இல்லை பயன்.",
  "தெள்ளூழ் என்பதோர் தெய்வம்; முயற்சி அதனை மாற்றிடும் மந்திரம்.",
  "செய்வினை செய்யற்க சோம்பேறிக் கண்ணே; முயற்சியே மனிதன் மதிப்பு.",
  "வினை விடுவார் வினைமுதல் காணார்; வினை முடித்தார் கண்ணே விளைவு.",
  "ஆற்றின் அளவறிந்து செய்து முயல்வான் வாற்றல் வளவிற்கே உரியது.",
  "இடும்பை யுடையவன் முயல்வான்; முயலின் இடும்பை இல்லாம் விடும்.",
  "செயற்கரிய தெய்வம் எனப்படும் முயற்சி; அதை விட வேறு தெய்வம் இல்லை.",
  "முயற்சி எனப்படுவது மனிதன் கையளவு; பலன் எனப்படுவது காலத்தின் கையளவு.",
  "வினை செயின் வினை செய்யல் வேண்டு; வினை செய்யின் வினை முயற்சி வேண்டு.",
  "கற்றது கைமண் அளவு; கல்லாதது உலகளவு.",
  "கற்க கசடறக் கற்பவை கற்றபின் நெறிக்கேட்டு நடக்க வேண்டும்.",
  "கற்றவர் உலகில் உயர்வார் கற்றிலார்; கதவுக்கு வெளியே நிற்பர்.",
  "கல்வி எனப்படுவது பயனுடையது; பயனில்லாத கல்வி சுமை.",
  "அறிவுடையாரின் சொல் நன்மை தரும்; அறியாதோரின் சொல் துன்பம் தரும்.",
  "அறிவே உலகில் உயர்ந்த செல்வம்; மற்ற செல்வம் நிலையற்றது.",
  "எண்ணி துணிக; கருமம் துணிந்தபின் எண்ண வேண்டாம்.",
  "யாதனின் யாதனின் நீங்கியான் நோதல் அதனின் அதனின் இலன்.",
  "தன்னிடம் குறை இருந்தும் முயலாது விடுதல் மிகக் குறை.",
  "அஞ்சும் பொருளும் முயற்சியும் கைகூடும்; துணிந்து செயின்.",
  "கடிந்த பயனில் கருதிச் செயலானும்; நெடிந்த பயனில் நெடிது முயற்சி.",
  "சோம்பல் எனப்படும் நோய்தான்; அதனை நீக்கின் உயர்வு உண்டாம்.",
  "உழைப்பே உயிர்க்கு உணவு; உழைக்காதவர் வாழ்வும் இல்லை.",
  "தீமை நிகழ்வதை ஊழென எண்ணாதே; முயற்சியால் மாற்றிடலாம்.",
  "வினை செய்யும் போது விடாமுயற்சி வேண்டும்; விட்டுவிட்டவனுக்கு பலன் இல்லை.",
  "உலகில் எல்லாம் முடிவது முயற்சியால்; முயலாதார் கருதும் விதியே அல்ல.",
];

export const DB_ACTIONS = {
  READ: "READ",
  WRITE: "WRITE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  CLEAR: "CLEAR",
};
